// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace FlightTicketApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240129121203_FlightSeed")]
    partial class FlightSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Entities.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirportId");

                    b.ToTable("Airport");

                    b.HasData(
                        new
                        {
                            AirportId = 1,
                            ArrivalAirport = "İstanbul/Sabiha Gökçen Airport",
                            DepartureAirport = "İstanbul/Sabiha Gökçen Airport"
                        },
                        new
                        {
                            AirportId = 2,
                            ArrivalAirport = "İstanbul/İstanbul Airport",
                            DepartureAirport = "İstanbul/İstanbul Airport"
                        },
                        new
                        {
                            AirportId = 3,
                            ArrivalAirport = "İzmir/Adnan Menderes Airport",
                            DepartureAirport = "İzmir/Adnan Menderes Airport"
                        },
                        new
                        {
                            AirportId = 4,
                            ArrivalAirport = "Muğla/Dalaman Airport",
                            DepartureAirport = "Muğla/Dalaman Airport"
                        },
                        new
                        {
                            AirportId = 5,
                            ArrivalAirport = "Antalya/Antalya Airport",
                            DepartureAirport = "Antalya/Antalya Airport"
                        },
                        new
                        {
                            AirportId = 6,
                            ArrivalAirport = "Mersin/Çukurova Airport",
                            DepartureAirport = "Mersin/Çukurova Airport"
                        });
                });

            modelBuilder.Entity("Entities.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableSeat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOneWayTicket")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 2,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 1,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 3,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 4,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 5,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 6,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 7,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 8,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 9,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 10,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 11,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 12,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 13,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 14,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 15,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 16,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 17,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 18,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 5),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 19,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 6),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 20,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 1, 31),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 4)
                        },
                        new
                        {
                            FlightId = 21,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 22,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 23,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 2, 5),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 24,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 6),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 25,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 1, 31),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 4)
                        },
                        new
                        {
                            FlightId = 26,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 27,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 28,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 29,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 30,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 31,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 32,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 33,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 34,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 5),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 35,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(524, 2, 5)
                        },
                        new
                        {
                            FlightId = 36,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 37,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 38,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 39,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 40,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 41,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 42,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 43,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 44,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 5),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 45,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 6),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 46,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 1, 31),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 4)
                        },
                        new
                        {
                            FlightId = 47,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 48,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 6),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 49,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 1, 31),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 4)
                        },
                        new
                        {
                            FlightId = 50,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(14, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(12, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 51,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(14, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 52,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(14, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 53,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(14, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 54,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(14, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 55,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(14, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 56,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(14, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 57,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(14, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 58,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(14, 0, 0),
                            IsOneWayTicket = true,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 59,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 60,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 61,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 62,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 63,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 64,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 65,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 1,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 66,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 2,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 67,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 68,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 69,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 70,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 71,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 72,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 2, 2),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 6)
                        },
                        new
                        {
                            FlightId = 73,
                            ArrivalAirportId = 1,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 3),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 8)
                        },
                        new
                        {
                            FlightId = 74,
                            ArrivalAirportId = 2,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 75,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 76,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 5),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 77,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 3,
                            DepartureDate = new DateOnly(2024, 2, 6),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 78,
                            ArrivalAirportId = 5,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 1, 31),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 4)
                        },
                        new
                        {
                            FlightId = 79,
                            ArrivalAirportId = 6,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 80,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 4,
                            DepartureDate = new DateOnly(2024, 2, 4),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 81,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 2, 5),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 82,
                            ArrivalAirportId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 6),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 10)
                        },
                        new
                        {
                            FlightId = 83,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 5,
                            DepartureDate = new DateOnly(2024, 1, 31),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 4)
                        },
                        new
                        {
                            FlightId = 84,
                            ArrivalAirportId = 4,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            AvailableSeat = 400,
                            DepartureAirportId = 6,
                            DepartureDate = new DateOnly(2024, 2, 1),
                            DepartureTime = new TimeOnly(10, 0, 0),
                            IsOneWayTicket = false,
                            ReturnDate = new DateOnly(2024, 2, 5)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
