// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace FlightTicketApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Entities.Flight", b =>
                {
                    b.Property<int?>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            ArrivalAirport = "İzmir/Adnan Menderes Airport",
                            DepartureAirport = "İstanbul/Sabiha Gökçen Airport",
                            DepartureDate = new DateOnly(2024, 1, 25),
                            ReturnDate = new DateOnly(2024, 1, 28)
                        },
                        new
                        {
                            FlightId = 2,
                            ArrivalAirport = "İzmir/Adnan Menderes Airport",
                            DepartureAirport = "İstanbul/İstanbul Airport",
                            DepartureDate = new DateOnly(2024, 1, 26),
                            ReturnDate = new DateOnly(2024, 1, 29)
                        },
                        new
                        {
                            FlightId = 3,
                            ArrivalAirport = "Muğla/Dalaman Airport",
                            DepartureAirport = "İstanbul/Sabiha Gökçen Airport",
                            DepartureDate = new DateOnly(2024, 1, 27),
                            ReturnDate = new DateOnly(2024, 1, 30)
                        },
                        new
                        {
                            FlightId = 4,
                            ArrivalAirport = "Muğla/Dalaman Airport",
                            DepartureAirport = "İstanbul/İstanbul Airport",
                            DepartureDate = new DateOnly(2024, 1, 28),
                            ReturnDate = new DateOnly(2024, 1, 31)
                        },
                        new
                        {
                            FlightId = 5,
                            ArrivalAirport = "İstanbul/Sabiha Gökçen Airport",
                            DepartureAirport = "İzmir/Adnan Menderes Airport",
                            DepartureDate = new DateOnly(2024, 1, 28),
                            ReturnDate = new DateOnly(2024, 2, 1)
                        },
                        new
                        {
                            FlightId = 6,
                            ArrivalAirport = "İstanbul/İstanbul Airport",
                            DepartureAirport = "İzmir/Adnan Menderes Airport",
                            DepartureDate = new DateOnly(2024, 1, 29),
                            ReturnDate = new DateOnly(2024, 2, 2)
                        },
                        new
                        {
                            FlightId = 7,
                            ArrivalAirport = "Muğla/Dalaman Airport",
                            DepartureAirport = "İzmir/Adnan Menderes Airport",
                            DepartureDate = new DateOnly(2024, 1, 30),
                            ReturnDate = new DateOnly(2024, 2, 3)
                        },
                        new
                        {
                            FlightId = 8,
                            ArrivalAirport = "İzmir/Adnan Menderes Airport",
                            DepartureAirport = "Muğla/Dalaman Airport",
                            DepartureDate = new DateOnly(2024, 1, 31),
                            ReturnDate = new DateOnly(2024, 2, 4)
                        },
                        new
                        {
                            FlightId = 9,
                            ArrivalAirport = "İstanbul/Sabiha Gökçen Airport",
                            DepartureAirport = "Muğla/Dalaman Airport",
                            DepartureDate = new DateOnly(2024, 2, 1),
                            ReturnDate = new DateOnly(2024, 2, 5)
                        },
                        new
                        {
                            FlightId = 10,
                            ArrivalAirport = "İstanbul/İstanbul Airport",
                            DepartureAirport = "Muğla/Dalaman Airport",
                            DepartureDate = new DateOnly(2024, 2, 2),
                            ReturnDate = new DateOnly(2024, 2, 6)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
